"""add Image table for merchandise

Revision ID: 23275c04606e
Revises: fbeba718e787
Create Date: 2025-03-26 04:36:52.135295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23275c04606e'
down_revision = 'fbeba718e787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('merchandise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchandise_id'], ['merchandise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.drop_table('image')
    # ### end Alembic commands ###
