"""Add Image model for merch and gallery

Revision ID: 2a7f3a1073ec
Revises: d6315b636e18
Create Date: 2025-03-26 10:32:36.367997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7f3a1073ec'
down_revision = 'd6315b636e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###
